#
# .tmux.conf
#
# This file contains only configuration statements and should not
# create sessions, windows, or panes. See .tmux.<session-name>.conf for that.
#

set -g prefix C-x

set -g base-index 1
set -g default-terminal screen-256color
set -as terminal-features ",screen-256color:RGB" # 24-bit color
set -g escape-time 50
set -g status-interval 1
set -g status on

set -g alternate-screen off
set -g automatic-rename on
set -g mode-keys vi
set -g mouse on

set-environment -g SSH_AUTH_SOCK ~/.ssh/auth-sock
set -g update-environment -r

# Nord theme for tmux https://github.com/nordtheme/tmux
set -g status-left "#[fg=black,bg=blue,bold] #S #[fg=blue,bg=black,nobold,noitalics,nounderscore]"
set -g status-right "#{prefix_highlight}#[fg=brightblack,bg=black,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] %H:%M #[fg=cyan,bg=brightblack,nobold,noitalics,nounderscore]#[fg=black,bg=cyan,bold] #H "
set -g status-justify left
set -g status-style bg=black,fg=white
 set -g window-status-format "#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I:#W#F #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I:#W#F #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-separator ""

set -g pane-border-style bg=default,fg=brightblack
set -g pane-active-border-style bg=default,fg=blue
set -g display-panes-colour black
set -g display-panes-active-colour brightblack

set -g message-style bg=brightblack,fg=cyan
set -g message-command-style bg=brightblack,fg=cyan

# disable entering copy mode when click-dragging with the mouse
unbind -T root MouseDrag1Pane

# https://www.reddit.com/r/tmux/comments/3paqoi/tmux_21_has_been_released/cw5ht4t
bind -T root WheelUpPane if -Ft= '#{mouse_any_flag}' 'send-keys -M' 'if -Ft= "#{pane_in_mode}" "send-keys -M" "copy-mode -u"'

# enable use of wheel mouse scrolling in tmux copy mode
bind -T copy-mode-vi WheelUpPane send-keys -X page-up
bind -T copy-mode-vi WheelDownPane send-keys -X page-down

bind -n F1 select-window -t :1
bind -n F2 select-window -t :2
bind -n F3 select-window -t :3
bind -n F4 select-window -t :4
bind -n F5 select-window -t :5
bind -n F6 select-window -t :6
bind -n F7 select-window -t :7
bind -n F8 select-window -t :8
bind -n F9 select-window -t :9
bind -n F10 select-window -t :10
bind -n F11 select-window -t :11
bind -n F12 select-window -t :12
# split window in current working directory
bind '%' split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|ssh)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
bind-key -n 'C-\' if-shell "$is_vim" 'send-keys C-\\' 'select-pane -l'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
